id: P008024
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14709
  title: བོད་ལྗོངས་སུ་བསྐྱོད་པ། སྲོག་ཆགས་དང་སྐྱེ་དངོས་སྣེ་མང་རང་བཞིན་དང་སྲུང་སྐྱོབ་བྱ་གཞག
  author: ''
  volumes:
    ff30656665cc4cfbb35e67a58bd4dc4c:
      image_group_id: I2PD19785
      title: ''
      volume_number: 1
      total_pages: 134
ebook_metadata:
  title: བོད་ལྗོངས་སུ་བསྐྱོད་པ། སྲོག་ཆགས་དང་སྐྱེ་དངོས་སྣེ་མང་རང་བཞིན་དང་སྲུང་སྐྱོབ་བྱ་གཞག
  author: ''
  sku: P008024
  cover: cover.jpg
  layers:
  - pagination
