id: I24BA1F8D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:46:11+00:00'
last_modified: '2022-06-08T17:53:38.654062+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14709
  title: བོད་ལྗོངས་སུ་བསྐྱོད་པ། སྲོག་ཆགས་དང་སྐྱེ་དངོས་སྣེ་མང་རང་བཞིན་དང་སྲུང་སྐྱོབ་བྱ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8867':
      image_group_id: I2PD19785
      title: Volume 1 of bod ljongs su bskyod pa/ srog chags dang skye dngos sne mang
        rang bzhin dang srung skyob bya gzhag
      total_pages: 134
      order: 1
      base_file: 8867.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
